import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const dom=new JSDOM('<!DOCTYPE html><html><body><div id="root"></div></body></html>',{url:'http://localhost/'});
for(const key of ['window','document','HTMLElement','HTMLInputElement','Event','MouseEvent','File','Blob','localStorage'])globalThis[key]=key==='window'?dom.window:dom.window[key];
Object.defineProperty(globalThis,'navigator',{value:dom.window.navigator,configurable:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const report=JSON.parse(readFileSync('public/data/demo.json','utf8'));
globalThis.fetch=async()=>({ok:true,json:async()=>report});
let downloads=0;URL.createObjectURL=()=>{downloads++;return 'blob:test'};URL.revokeObjectURL=()=>{};
dom.window.HTMLAnchorElement.prototype.click=function(){};
const React=await import('react');const {act}=React;
const {createRoot}=await import('react-dom/client');
const {default:Homology}=await import('../app/page.tsx');
const root=createRoot(document.getElementById('root'));
const text=()=>document.body.textContent;
const buttons=()=>Array.from(document.querySelectorAll('button'));
const button=name=>{const found=buttons().find(b=>b.textContent===name);assert.ok(found,'Button '+name);return found};
const click=async el=>{await act(async()=>{el.dispatchEvent(new dom.window.MouseEvent('click',{bubbles:true}));await Promise.resolve()})};
await act(async()=>{root.render(React.createElement(Homology));await new Promise(r=>setTimeout(r,10))});
assert.ok(text().includes('合成数据 · 以下所有模型输出仅用于演示。'));
assert.equal(document.querySelectorAll('.stock').length,30);
assert.equal(document.querySelectorAll('.network [role="button"]').length,30);
await click(button('EN'));assert.equal(document.documentElement.lang,'en');assert.ok(text().includes('SYNTHETIC DATA'));
await click(button('60D'));assert.ok(text().includes('60D · Vietoris–Rips'));
await click(button('H₀'));assert.ok(document.querySelector('.diagram').getAttribute('aria-label').includes('H0'));
await click(document.querySelector('.stock-list .stock:nth-child(2)'));assert.ok(document.querySelector('.instrument-bar').textContent.includes('AMD'));
await click(button('Forecast'));assert.equal(document.querySelectorAll('.forecast-cards>div').length,3);
await click(button('Volatility · 20D'));assert.ok(text().includes('annualized RMS volatility'));
await click(button('Backtest'));assert.ok(text().includes('QLIKE'));assert.ok(text().includes('Split audit'));
await click(button('Regime · 20D'));assert.ok(text().includes('Probability calibration'));
await click(button('Method'));assert.ok(text().includes('not corrected for multiple assets'));
await click(button('Export report'));assert.equal(downloads,1);
const input=document.querySelector('input[type="file"]');
const file={size:123,text:async()=>'{"schemaVersion":99}'};
Object.defineProperty(input,'files',{value:[file],configurable:true});
await act(async()=>{input.dispatchEvent(new dom.window.Event('change',{bubbles:true}));await Promise.resolve()});assert.ok(document.querySelector('[role="alert"]'));
const imported=structuredClone(report);imported.source.kind='imported';imported.source.label='Test adjusted-history input';
Object.defineProperty(input,'files',{value:[{size:100,text:async()=>JSON.stringify(imported)}],configurable:true});
await act(async()=>{input.dispatchEvent(new dom.window.Event('change',{bubbles:true}));await Promise.resolve()});assert.ok(text().includes('IMPORTED DATA'));assert.equal(document.querySelector('[role="alert"]'),null);
await click(button('Reset to demo'));assert.ok(text().includes('SYNTHETIC DATA'));
await act(async()=>root.unmount());
console.log('DOM interaction QA: language, scale, H0/H1, target selection, tabs, all target types, calibration, export, invalid/valid import and demo reset passed. Layout and real browser behavior remain unverified.');
