import {Diagram,Report,Snapshot} from '@/lib/report';
const blue='#315b99',copper='#bb704f';
export function Geometry({snapshot,symbols,selected,epsilon,zh,onSelect}:{snapshot:Snapshot;symbols:string[];selected:string;epsilon:number;zh:boolean;onSelect:(s:string)=>void}){
 const n=symbols.length;
 // Circular layout keeps vertices identifiable; distances are represented by edges, not screen length.
 const points=symbols.map((_,i)=>{const a=2*Math.PI*i/n-Math.PI/2;const radius=i%2===0?154:126;return {x:300+radius*Math.cos(a),y:190+radius*Math.sin(a)}});
 const edges: [number,number][]=[];let triangleCount=0;
 for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)if(snapshot.distance[i][j]<=epsilon)edges.push([i,j]);
 for(let i=0;i<n;i++)for(let j=i+1;j<n;j++)for(let k=j+1;k<n;k++)if(snapshot.distance[i][j]<=epsilon&&snapshot.distance[i][k]<=epsilon&&snapshot.distance[j][k]<=epsilon)triangleCount++;
 const parent=Array.from({length:n},(_,i)=>i);const root=(i:number):number=>parent[i]===i?i:(parent[i]=root(parent[i]));edges.forEach(([i,j])=>{parent[root(i)]=root(j)});const components=new Set(parent.map((_,i)=>root(i))).size;
 const active=symbols.indexOf(selected);
 return <><div className="graph-meta"><span>{zh?'顶点':'VERTICES'} <b>{n}</b></span><span>{zh?'边':'EDGES'} <b>{edges.length}</b></span><span>{zh?'连通分量':'COMPONENTS'} <b>{components}</b></span><span>{zh?'填充三角形':'FILLED TRIANGLES'} <b>{triangleCount}</b></span></div><svg viewBox="0 0 600 390" className="network" role="img" aria-label={zh?'相关距离过滤网络，圆形布局不代表资产之间的实际距离':'Correlation-distance filtration network. Circular layout is not a distance embedding.'}><circle cx="300" cy="190" r="170" fill="none" stroke="#edf1f4"/><circle cx="300" cy="190" r="105" fill="none" stroke="#edf1f4"/>{edges.map(([i,j])=><line key={`${i}-${j}`} x1={points[i].x} y1={points[i].y} x2={points[j].x} y2={points[j].y} stroke={i===active||j===active?blue:'#c7d4e0'} strokeWidth={i===active||j===active?1.5:.65} opacity={(i===active||j===active)? .85:.5}/>)}{points.map((p,i)=><g key={symbols[i]} className="node" onClick={()=>onSelect(symbols[i])} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(symbols[i])}}} tabIndex={0} role="button" aria-label={symbols[i]}><circle cx={p.x} cy={p.y} r={i===active?7:4} fill={i===active?copper:blue} stroke="white" strokeWidth="2"/><text x={p.x+(p.x<300?-9:9)} y={p.y+4} textAnchor={p.x<300?'end':'start'} fill={i===active?copper:'#49677c'} fontSize={i===active?13:10}>{symbols[i]}</text><title>{symbols[i]}</title></g>)}</svg><div className="plot-caption">{zh?'圆形布局仅用于定位。所有三角形在 VR 中都被填充；图上的环不一定是 H₁。':'Circular layout for identification. Every triangle is filled in VR; a graph cycle need not be an H₁ class.'}</div></>;
}
export function Persistence({snapshot,dimension,epsilon,zh}:{snapshot:Snapshot;dimension:0|1;epsilon:number;zh:boolean}){
 const diagram=dimension===0?snapshot.h0:snapshot.h1,x=(n:number)=>45+n*112,y=(n:number)=>270-n*112;
 return <svg viewBox="0 0 300 315" className="diagram" role="img" aria-label={zh?`H${dimension} 出生死亡图`:`H${dimension} persistence diagram`}><rect x="45" y="46" width="224" height="224" fill="#f8fafc"/>{[0,.5,1,1.5,2].map(n=><g key={n}><line x1={45} x2={269} y1={y(n)} y2={y(n)} stroke="#e5ebf0"/><text x="32" y={y(n)+4} textAnchor="end" className="axis">{n.toFixed(1)}</text><text x={x(n)} y="291" textAnchor="middle" className="axis">{n.toFixed(1)}</text></g>)}<line x1="45" y1="270" x2="269" y2="46" stroke="#9cabb8" strokeDasharray="4 4"/><line x1={x(epsilon)} x2={x(epsilon)} y1="46" y2="270" stroke={copper} opacity=".5" strokeDasharray="3 4"/>{diagram.map((p,i)=><circle key={i} cx={x(p[0])} cy={y(p[1])} r="4" stroke="white" fill={p[0]<=epsilon&&p[1]>epsilon?copper:blue} opacity=".8"><title>{`H${dimension} · birth ${p[0].toFixed(4)} · death ${p[1].toFixed(4)} · persistence ${(p[1]-p[0]).toFixed(4)}`}</title></circle>)}<text x="156" y="312" textAnchor="middle" className="axis">{zh?'出生':'Birth'}</text><text x="12" y="157" transform="rotate(-90,12,157)" textAnchor="middle" className="axis">{zh?'死亡':'Death'}</text></svg>;
}
export function Landscape({diagram,zh}:{diagram:Diagram;zh:boolean}){
 const pts=Array.from({length:81},(_,i)=>{const e=i/40;return [35+e*245,100-80*Math.max(0,...diagram.map(([b,d])=>Math.min(e-b,d-e)))]});
 return <svg viewBox="0 0 550 130" role="img" className="landscape" aria-label={zh?'第一层持久景观':'First persistence landscape layer'}><line x1="35" x2="525" y1="100" y2="100" stroke="#dce3e7"/><path d={'M'+pts.map(p=>p.join(',')).join(' L')+' L525,100 L35,100 Z'} fill="#eaf0f7"/><polyline points={pts.map(p=>p.join(',')).join(' ')} fill="none" stroke={blue} strokeWidth="2"/><text x="35" y="121" className="axis">0</text><text x="525" y="121" className="axis">2 ε</text><text x="12" y="26" className="axis">λ₁</text></svg>;
}
export function Timeline({report,zh}:{report:Report;zh:boolean}){
 const history=report.timeline.slice(-180);const max=Math.max(1e-9,...history.flatMap(t=>report.windows.map(w=>t.scales[w].h1.velocity)));
 return <><div className="heatmap">{report.windows.map(w=><div className="heat-row" key={w}><span>{w}D</span><div>{history.map(t=><i key={t.date} style={{background:`rgba(49,91,153,${.06+.94*t.scales[w].h1.velocity/max})`}} title={`${t.date} · ${w}D H₁ W₂ ${t.scales[w].h1.velocity.toFixed(5)}`}/>)}</div></div>)}</div><div className="plot-caption spread"><span>{history[0].date}</span><span>{zh?'H₁ W₂ 速度 · 共用色阶':'H₁ W₂ velocity · shared color scale'}</span><span>{history.at(-1)!.date}</span></div></>;
}
export function LineChart({series,labels,zh}:{series:number[][];labels:string[];zh:boolean}){
 const flat=series.flat();const min=Math.min(...flat),max=Math.max(...flat);const x=(i:number)=>42+i*560/Math.max(1,series[0].length-1),y=(v:number)=>180-150*(v-min)/Math.max(max-min,1e-8);
 return <svg viewBox="0 0 650 220" className="linechart" role="img" aria-label={zh?'样本外预测与结果':'Out-of-sample predictions and outcomes'}>{[0,.5,1].map(f=><g key={f}><line x1="42" x2="602" y1={30+150*f} y2={30+150*f} stroke="#e6ebf0"/><text x="33" y={34+150*f} textAnchor="end" className="axis">{(max-f*(max-min)).toFixed(3)}</text></g>)}{series.map((s,j)=><polyline key={j} points={s.map((v,i)=>`${x(i)},${y(v)}`).join(' ')} fill="none" stroke={['#93a7b7',blue,copper][j]} strokeWidth="1.5"/>)}<text x="42" y="207" className="axis">{labels[0]}</text><text x="602" y="207" textAnchor="end" className="axis">{labels.at(-1)}</text></svg>;
}
