export type Task='direction'|'volatility'|'regime';
export type Diagram=number[][];
export type Summary={energy:number;total:number;maximum:number;entropy:number;velocity:number;acceleration:number;delta:number;delta2:number;count:number};
export type Snapshot={distance:number[][];h0:Diagram;h1:Diagram};
export type State={h0:Summary;h1:Summary;meanCorrelation:number};
export type Metrics={model:string;brier?:number;logLoss?:number;balancedAccuracy?:number;auc?:number|null;qlike?:number;mae?:number;rmse?:number};
export type Fold={origin:string;trainEnd:string;labelEnd:string;trainCount:number;testCount:number;threshold:number|null};
export type Row={date:string;actual:number;predictions:number[];threshold:number|null};
export type Calibration={bin:number;count:number;predicted:number|null;observed:number|null};
export type Result={horizon:number;metrics:Metrics[];lossImprovement:number;interval95:(number|null)[];evidence:'positive'|'inconclusive'|'negative';latest:number[];latestThreshold:number|null;latestTrainCount:number;rows:Row[];folds:Fold[];calibration:Calibration[][]};
export type Report={schemaVersion:1;source:{kind:'synthetic'|'imported';label:string;adjustment:string;researchOnly:boolean};asOf:string;symbols:string[];windows:number[];snapshots:Record<string,Snapshot>;timeline:{date:string;scales:Record<string,State>}[];targets:Record<string,Record<Task,Result>>;method:{minTrain:number;refitEvery:number;labelAvailability:string;groundMetric:string;w2Order:number;features:number[];seed:number;bootstrapBlock:number;bootstrapReplicates:number;versions:Record<string,string>;dataHash:string;observations:number};surrogate:{kind:string;covarianceMaxError:number;interpretation:string}};
// Import schema is closed to the supported method so an arbitrary JSON does not masquerade as a validated result.
export function validateReport(value:unknown):Report{
 const r=value as Report;
 const finite=(v:unknown):v is number=>typeof v==='number'&&Number.isFinite(v);
 const date=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v);
 const fail=()=>{throw new Error('Unsupported or invalid research report. Generate it with python/research.py.');};
 if(!r||r.schemaVersion!==1||!['synthetic','imported'].includes(r.source?.kind)||typeof r.source.label!=='string'||typeof r.source.adjustment!=='string'||r.source.researchOnly!==true||!date(r.asOf)||!Array.isArray(r.symbols)||r.symbols.length<30||r.symbols.length>50||new Set(r.symbols).size!==r.symbols.length||r.symbols.some(s=>typeof s!=='string'||!s.length||s.length>60||['__proto__','constructor','prototype'].includes(s))||JSON.stringify(r.windows)!=='[20,60,120]')return fail();
 if(r.method?.minTrain!==252||r.method.refitEvery!==20||r.method.labelAvailability!=='labelEnd < forecastOrigin'||r.method.groundMetric!=='Euclidean'||r.method.w2Order!==2||r.method.bootstrapReplicates!==1000||!finite(r.method.observations)||!Array.isArray(r.method.features)||JSON.stringify(r.method.features)!=='[6,21,69]'||typeof r.method.dataHash!=='string'||!r.surrogate||!finite(r.surrogate.covarianceMaxError))return fail();
 for(const w of r.windows){const s=r.snapshots?.[w];if(!s||!Array.isArray(s.distance)||s.distance.length!==r.symbols.length)return fail();for(let i=0;i<s.distance.length;i++){if(s.distance[i].length!==r.symbols.length)return fail();for(let j=0;j<s.distance.length;j++)if(!finite(s.distance[i][j])||s.distance[i][j]<0||s.distance[i][j]>2.00001||Math.abs(s.distance[i][j]-s.distance[j]?.[i])>1e-6||(i===j&&s.distance[i][j]!==0))return fail();}for(const d of [s.h0,s.h1])if(!Array.isArray(d)||d.some(p=>p.length!==2||!p.every(finite)||p[0]<0||p[1]>2.00001||p[0]>=p[1]))return fail();}
 if(!Array.isArray(r.timeline)||!r.timeline.length||r.timeline.length>12000)return fail();
 for(let i=0;i<r.timeline.length;i++){const t=r.timeline[i];if(!date(t.date)||(i>0&&r.timeline[i-1].date>=t.date))return fail();for(const w of r.windows){const s=t.scales?.[w];if(!s||!finite(s.meanCorrelation))return fail();for(const k of ['h0','h1'] as const)if(!s[k]||['energy','total','maximum','entropy','velocity','acceleration','delta','delta2','count'].some(key=>!finite(s[k][key as keyof Summary])))return fail();}}
 if(r.timeline.at(-1)?.date!==r.asOf||!r.targets||!Object.keys(r.targets).length)return fail();
 for(const [symbol, tasks] of Object.entries(r.targets)){if(!r.symbols.includes(symbol))return fail();for(const task of ['direction','volatility','regime'] as const){const result=tasks[task];if(!result||result.horizon!==(task==='direction'?5:20)||!Array.isArray(result.latest)||result.latest.length!==3||!result.latest.every(finite)||result.latest.some(p=>p<0||(task!=='volatility'&&p>1))||!['positive','negative','inconclusive'].includes(result.evidence)||!finite(result.lossImprovement)||!Array.isArray(result.interval95)||result.interval95.length!==2||result.interval95.some(p=>p!==null&&!finite(p)))return fail();if(result.metrics?.length!==3||!Array.isArray(result.rows)||!result.rows.length||result.rows.length>12000||!Array.isArray(result.folds)||!result.folds.length)return fail();for(const m of result.metrics){if(typeof m.model!=='string'||!Object.values(m).every(v=>typeof v==='string'||v===null||finite(v)))return fail();}for(let i=0;i<result.rows.length;i++){const row=result.rows[i];if(!date(row.date)||!finite(row.actual)||row.predictions?.length!==3||!row.predictions.every(finite)||row.predictions.some(p=>p<0||(task!=='volatility'&&p>1))||(task!=='volatility'&&row.actual!==0&&row.actual!==1)||(i>0&&result.rows[i-1].date>=row.date))return fail();}for(const f of result.folds)if(!date(f.origin)||!date(f.trainEnd)||!date(f.labelEnd)||f.labelEnd>=f.origin||f.trainEnd>f.labelEnd||f.trainCount<252)return fail();if(!Array.isArray(result.calibration)||!finite(result.latestTrainCount)||result.latestTrainCount<252||(result.latestThreshold!==null&&!finite(result.latestThreshold)))return fail();if(task!=='volatility'){if(result.calibration.length!==3)return fail();for(const bins of result.calibration){if(!Array.isArray(bins)||bins.length!==10)return fail();for(const b of bins)if(!b||!finite(b.bin)||!Number.isInteger(b.count)||b.count<0||b.count>result.rows.length||(b.predicted!==null&&(!finite(b.predicted)||b.predicted<0||b.predicted>1))||(b.observed!==null&&(!finite(b.observed)||b.observed<0||b.observed>1)))return fail();}}}}
 return r;
}
